repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: format
        name: Check code formatting
        entry: make cq/format/check
        language: system
        pass_filenames: false
      - id: lint
        name: Lint code
        entry: make cq/lint
        language: system
        pass_filenames: false
      - id: typecheck
        name: Typecheck code
        entry: make cq/typecheck
        language: system
        pass_filenames: false
      - id: test
        name: Test code
        entry: make cq/test
        language: system
        pass_filenames: false
