version: 1
disable_existing_loggers: False

formatters:
  default:
    (): colorlog.ColoredFormatter
    format: "%(log_color)s%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    log_colors:
      DEBUG: cyan
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: bold_red

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [console]

loggers:
  uvicorn:
    level: DEBUG
    handlers: [console]
    propagate: True

  uvicorn.error:
    level: DEBUG
    handlers: [console]
    propagate: True

  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: True
